### ISSUE TITLE
InitialUris don't creates back history in browser

### ISSUE THREAD

**Issue by dees91** [Kleak/flouter#3]
First of all thanks for this project - it helped me a lot in understanding navigation 2.0

I have an issue with `initialUris` in flutter web. It is a list of `Uri` which would suggest that I can create initial routes stack. But when I'm passing 
```
initialUris: [
	Uri.parse('/'),
	Uri.parse('/test/toto/?limit=12'),
]
```
to `UriRouterDelegate` in your example, browser indeed open on `/test/toto/?limit=12` route but browser back button is disabled - I can't use it to back to previous `/` page - am I missing something or is it correct behaviour?

I'm using `Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.14.6 18G103 darwin-x64, locale en-US)` and `Chrome Version 87.0.4280.88 (Official Build) (x86_64)` - for mac os.

**Comment by Kleak** [comment]
Thanks for the kind word and I'm really happy it help you to understand what is happening under the hood :)

This is the correct current behavior but seems pretty weird in reality.
it's due to the fact that initial uris are pushed before the build function is triggered and the result is that you don't have animation and also not browser history.

it was primarily like that to eliminate the animation but that seems to not be a great solution as it break the browser history :/

Maybe we can found a better way of doing this.

**Comment by Kleak** [comment]
Is there some way in other web framework to do this ?

**Comment by Kleak** [comment]
It seems no other web framework are doing this.

But as you can see your app navigation history is populated so it should not be a real problem you can have your own back system like all other website like tweeter.

**Comment by Kleak** [comment]
I keep this open because we can probably have a flag to have this behavior ;)

will probably happen after #1 has landed

**Comment by dees91** [comment]
Thanks for the reply,

I'm not familiar with other web frameworks, it seemed intuitive to me and I wanted to make sure if perhaps I'm doing something wrong. 

Indeed app navigation history is populated so it's not a big problem for me.

For me issue can be closed, thanks again and keep up the good work.
